# # print("*****1******")
# # numero1 = int (input("inserte un numero: "))
# # numero2 = int (input("inserte un numero: "))
# # if (numero1%2 == 0) and (numero2%2== 0 ) :

# #     print(f'''{numero1} y {numero2} son pares''')
# # elif (numero1%2 == 0) or (numero2%2== 0 ) :
# #     print("ambos numeros no son pares")
# # else:
# #     print("estos numeros no son pares")

# # # print("*****2****")
# edad = int (input("insertu su edad: "))
# genero = (input("inserte su genero sindo M para masculino y F para femenino: ")).lower()
# if genero=="m" and edad>=60 :
#     print("te puedes jubilar ¡¡¡¡felicitaciones!!!!")
# elif genero=="m" and edad<60 :
#     print("no te puedes jubilar trabaja mas")
# elif genero=="f" and edad>=55 :
#     print("te puedes jubilar ¡¡¡¡felicitaciones!!!!")
# elif genero=="f" and edad<55 :
#     print("no te puedes jubilar trabaja mas")
# # print("forma dos")

# if genero=="m" and edad>=60 or genero=="f" and edad>=55 :
#     print("te puedes jubilar ¡¡¡¡felicitaciones!!!!")
# elif genero=="m" and edad<60 or genero=="f" and edad<55 :
#     print("no te puedes jubilar trabaja mas")

# # print("*****3****")
# print("Años bisiestos???")
# año = int (input("escriba un año: "))
# if ((año % 4==0 and año % 100!=0) or año%400==0):
#     print("Es bisiesto")
# else: print("No es viciesto")





